In [1]:
import joblib
import pandas as pd
import numpy as np

# utils, submit에서 필요한 함수 로드

import importlib
import utils as ut
importlib.reload(ut)

import submit as sb
importlib.reload(sb)

In [2]:
# 모델 로드
loaded_model = joblib.load("logit_model.pkl")
feature_cols = joblib.load("feature_cols.pkl")

loaded_model_sp = joblib.load("logit_model_sp.pkl")
feature_cols_sp = joblib.load("feature_cols_sp.pkl")
print("모델 로드 완료")

모델 로드 완료

### API에서 오늘 경기 데이터 행 불러오기

### Given lineup
- 날짜 변경 필수

In [3]:
# 예측용 데이터 생성
pred_result = ut.build_prediction_data_for_date( # gameState != 4로 정리완. 
    date_str="2026-04-21",                          # 예측 날짜
    sleep_sec=0.2,
    verbose=True
)

pred_df = pred_result["pred_df"]

=== 1. collect_games ===
[games] 2026-04-21: 5 rows
games_df.shape = (5, 21)

,game_id,game_date,season,home_team_code,away_team_code,stadium_code,home_sp_id,away_sp_id,home_sp_name,away_sp_name,...,away_score,home_win,game_state,game_time,weather,temperature,humidity,windDirection,windSpeed,rainprobability
0,20260101,2026-04-21 09:30:00,2026,5002,7002,1001,14846,15013,송승기,문동주,...,None,0,1,18:30:00,0,0,0,0,0,0
1,20260102,2026-04-21 09:30:00,2026,10001,11001,1003,12860,16630,오석주,버하겐,...,None,0,1,18:30:00,0,0,0,0,0,0
2,20260103,2026-04-21 09:30:00,2026,12001,2002,2002,14581,16250,오원석,김태형,...,None,0,1,18:30:00,0,0,0,0,0,0
3,20260104,2026-04-21 09:30:00,2026,1001,9002,7003,11379,16446,최원태,베니지아노,...,None,0,1,18:30:00,0,0,0,0,0,0
4,20260105,2026-04-21 09:30:00,2026,3001,6002,8001,12930,15143,나균안,벤자민,...,None,0,1,18:30:00,0,0,0,0,0,0

=== 2. filter target games ===
games_pred.shape = (5, 21)

,game_id,game_date,season,home_team_code,away_team_code,stadium_code,home_sp_id,away_sp_id,home_sp_name,away_sp_name,...,away_score,home_win,game_state,game_time,weather,temperature,humidity,windDirection,windSpeed,rainprobability
0,20260101,2026-04-21 09:30:00,2026,5002,7002,1001,14846,15013,송승기,문동주,...,None,0,1,18:30:00,0,0,0,0,0,0
1,20260102,2026-04-21 09:30:00,2026,10001,11001,1003,12860,16630,오석주,버하겐,...,None,0,1,18:30:00,0,0,0,0,0,0
2,20260103,2026-04-21 09:30:00,2026,12001,2002,2002,14581,16250,오원석,김태형,...,None,0,1,18:30:00,0,0,0,0,0,0
3,20260104,2026-04-21 09:30:00,2026,1001,9002,7003,11379,16446,최원태,베니지아노,...,None,0,1,18:30:00,0,0,0,0,0,0
4,20260105,2026-04-21 09:30:00,2026,3001,6002,8001,12930,15143,나균안,벤자민,...,None,0,1,18:30:00,0,0,0,0,0,0

=== 3. collect_lineups ===
[lineup] 20260101: 2 rows
[lineup] 20260102: 2 rows
[lineup] 20260103: 2 rows
[lineup] 20260104: 2 rows
[lineup] 20260105: 2 rows
lineup_df.shape = (10, 13)
=== 4. collect_rosters ===
[roster] 2026-04-21 team=1001: 29 rows
[roster] 2026-04-21 team=2002: 29 rows
[roster] 2026-04-21 team=3001: 29 rows
[roster] 2026-04-21 team=5002: 29 rows
[roster] 2026-04-21 team=6002: 30 rows
[roster] 2026-04-21 team=7002: 29 rows
[roster] 2026-04-21 team=9002: 29 rows
[roster] 2026-04-21 team=10001: 29 rows
[roster] 2026-04-21 team=11001: 29 rows
[roster] 2026-04-21 team=12001: 29 rows
roster_df.shape = (291, 5)
n_unique_player_ids = 291
=== 5. collect_player_season ===
[playerSeason] 10363: OK
[playerSeason] 10640: OK
[playerSeason] 10527: OK
[playerSeason] 10232: OK
[playerSeason] 14113: OK
[playerSeason] 14116: OK
[playerSeason] 14618: OK
[playerSeason] 15034: OK
[playerSeason] 10894: OK
[playerSeason] 11422: OK
[playerSeason] 11489: OK
[playerSeason] 14616: OK
[playerSeason] 15036: OK
[playerSeason] 16162: OK
[playerSeason] 11379: OK
[playerSeason] 13157: OK
[playerSeason] 14121: OK
[playerSeason] 15531: OK
[playerSeason] 14122: OK
[playerSeason] 12941: OK
[playerSeason] 16239: OK
[playerSeason] 16241: OK
[playerSeason] 16242: OK
[playerSeason] 10891: OK
[playerSeason] 10909: OK
[playerSeason] 10344: OK
[playerSeason] 16412: OK
[playerSeason] 16423: OK
[playerSeason] 13574: OK
[playerSeason] 10058: OK
[playerSeason] 10008: OK
[playerSeason] 11298: OK
[playerSeason] 12540: OK
[playerSeason] 14788: OK
[playerSeason] 12869: OK
[playerSeason] 10659: OK
[playerSeason] 15056: OK
[playerSeason] 15063: OK
[playerSeason] 11162: OK
[playerSeason] 14176: OK
[playerSeason] 12567: OK
[playerSeason] 12944: OK
[playerSeason] 13113: OK
[playerSeason] 14611: OK
[playerSeason] 16085: OK
[playerSeason] 16088: OK
[playerSeason] 11126: OK
[playerSeason] 16250: OK
[playerSeason] 16252: OK
[playerSeason] 16261: OK
[playerSeason] 14764: OK
[playerSeason] 16344: OK
[playerSeason] 16289: OK
[playerSeason] 10609: OK
[playerSeason] 13151: OK
[playerSeason] 11411: OK
[playerSeason] 16425: OK
[playerSeason] 13592: OK
[playerSeason] 10266: OK
[playerSeason] 11310: OK
[playerSeason] 10825: OK
[playerSeason] 12930: OK
[playerSeason] 13155: OK
[playerSeason] 14169: OK
[playerSeason] 14624: OK
[playerSeason] 14642: OK
[playerSeason] 12699: OK
[playerSeason] 13169: OK
[playerSeason] 14792: OK
[playerSeason] 10804: OK
[playerSeason] 10753: OK
[playerSeason] 11165: OK
[playerSeason] 13271: OK
[playerSeason] 14796: OK
[playerSeason] 16091: OK
[playerSeason] 16092: OK
[playerSeason] 16106: OK
[playerSeason] 14590: OK
[playerSeason] 13073: OK
[playerSeason] 15051: OK
[playerSeason] 16267: OK
[playerSeason] 12572: OK
[playerSeason] 13145: OK
[playerSeason] 16429: OK
[playerSeason] 16430: OK
[playerSeason] 16433: OK
[playerSeason] 16434: OK
[playerSeason] 10475: OK
[playerSeason] 10652: OK
[playerSeason] 13056: OK
[playerSeason] 12546: OK
[playerSeason] 14137: OK
[playerSeason] 14669: OK
[playerSeason] 13112: OK
[playerSeason] 11094: OK
[playerSeason] 11190: OK
[playerSeason] 11166: OK
[playerSeason] 13103: OK
[playerSeason] 11229: OK
[playerSeason] 15532: OK
[playerSeason] 10387: OK
[playerSeason] 15084: OK
[playerSeason] 14140: OK
[playerSeason] 14781: OK
[playerSeason] 14816: OK
[playerSeason] 14783: OK
[playerSeason] 15081: OK
[playerSeason] 11164: OK
[playerSeason] 14846: OK
[playerSeason] 16274: OK
[playerSeason] 16286: OK
[playerSeason] 14134: OK
[playerSeason] 14606: OK
[playerSeason] 16404: OK
[playerSeason] 13104: OK
[playerSeason] 16398: OK
[playerSeason] 11098: OK
[playerSeason] 12568: OK
[playerSeason] 13061: OK
[playerSeason] 10195: OK
[playerSeason] 12524: OK
[playerSeason] 11087: OK
[playerSeason] 14770: OK
[playerSeason] 11213: OK
[playerSeason] 11300: OK
[playerSeason] 13070: OK
[playerSeason] 15099: OK
[playerSeason] 12894: OK
[playerSeason] 10165: OK
[playerSeason] 15508: OK
[playerSeason] 13124: OK
[playerSeason] 14736: OK
[playerSeason] 12549: OK
[playerSeason] 16067: OK
[playerSeason] 15104: OK
[playerSeason] 15253: OK
[playerSeason] 16287: OK
[playerSeason] 16288: OK
[playerSeason] 16293: OK
[playerSeason] 16299: OK
[playerSeason] 11261: OK
[playerSeason] 15512: OK
[playerSeason] 16426: OK
[playerSeason] 16457: OK
[playerSeason] 10261: OK
[playerSeason] 15143: OK
[playerSeason] 11117: OK
[playerSeason] 10913: OK
[playerSeason] 10170: OK
[playerSeason] 11414: OK
[playerSeason] 12585: OK
[playerSeason] 13138: OK
[playerSeason] 15013: OK
[playerSeason] 15014: OK
[playerSeason] 13003: OK
[playerSeason] 12871: OK
[playerSeason] 11215: OK
[playerSeason] 15421: OK
[playerSeason] 15422: OK
[playerSeason] 14707: OK
[playerSeason] 16107: OK
[playerSeason] 16108: OK
[playerSeason] 10590: OK
[playerSeason] 15015: OK
[playerSeason] 11334: OK
[playerSeason] 16301: OK
[playerSeason] 16302: OK
[playerSeason] 13168: OK
[playerSeason] 16121: OK
[playerSeason] 16414: OK
[playerSeason] 16415: OK
[playerSeason] 16421: OK
[playerSeason] 16424: OK
[playerSeason] 16458: OK
[playerSeason] 16631: OK
[playerSeason] 10106: OK
[playerSeason] 10815: OK
[playerSeason] 10783: OK
[playerSeason] 12571: OK
[playerSeason] 12922: OK
[playerSeason] 13126: OK
[playerSeason] 14587: OK
[playerSeason] 10249: OK
[playerSeason] 13228: OK
[playerSeason] 10203: OK
[playerSeason] 10707: OK
[playerSeason] 13128: OK
[playerSeason] 15461: OK
[playerSeason] 15530: OK
[playerSeason] 14153: OK
[playerSeason] 10312: OK
[playerSeason] 14805: OK
[playerSeason] 16042: OK
[playerSeason] 14803: OK
[playerSeason] 14804: OK
[playerSeason] 15121: OK
[playerSeason] 13167: OK
[playerSeason] 15032: OK
[playerSeason] 16321: OK
[playerSeason] 16324: OK
[playerSeason] 11153: OK
[playerSeason] 10643: OK
[playerSeason] 16446: OK
[playerSeason] 15028: OK
[playerSeason] 11222: OK
[playerSeason] 13091: OK
[playerSeason] 11225: OK
[playerSeason] 14580: OK
[playerSeason] 11161: OK
[playerSeason] 15472: OK
[playerSeason] 15473: OK
[playerSeason] 12516: OK
[playerSeason] 14591: OK
[playerSeason] 10182: OK
[playerSeason] 12860: OK
[playerSeason] 16130: OK
[playerSeason] 10557: OK
[playerSeason] 16327: OK
[playerSeason] 16330: OK
[playerSeason] 16384: OK
[playerSeason] 13941: OK
[playerSeason] 11425: OK
[playerSeason] 14809: OK
[playerSeason] 10014: OK
[playerSeason] 13094: OK
[playerSeason] 14849: OK
[playerSeason] 12858: OK
[playerSeason] 15068: OK
[playerSeason] 16408: OK
[playerSeason] 16410: OK
[playerSeason] 16441: OK
[playerSeason] 16451: OK
[playerSeason] 16453: OK
[playerSeason] 11137: OK
[playerSeason] 13081: OK
[playerSeason] 13085: OK
[playerSeason] 13088: OK
[playerSeason] 12897: OK
[playerSeason] 11355: OK
[playerSeason] 12560: OK
[playerSeason] 14765: OK
[playerSeason] 14220: OK
[playerSeason] 13082: OK
[playerSeason] 10189: OK
[playerSeason] 14156: OK
[playerSeason] 15111: OK
[playerSeason] 11329: OK
[playerSeason] 13261: OK
[playerSeason] 11248: OK
[playerSeason] 13250: OK
[playerSeason] 14221: OK
[playerSeason] 16057: OK
[playerSeason] 16066: OK
[playerSeason] 14766: OK
[playerSeason] 11353: OK
[playerSeason] 11099: OK
[playerSeason] 15115: OK
[playerSeason] 16442: OK
[playerSeason] 16450: OK
[playerSeason] 16454: OK
[playerSeason] 16480: OK
[playerSeason] 16630: OK
[playerSeason] 11317: OK
[playerSeason] 11323: OK
[playerSeason] 10235: OK
[playerSeason] 13006: OK
[playerSeason] 11212: OK
[playerSeason] 14106: OK
[playerSeason] 14600: OK
[playerSeason] 14603: OK
[playerSeason] 11308: OK
[playerSeason] 11397: OK
[playerSeason] 15089: OK
[playerSeason] 11214: OK
[playerSeason] 10320: OK
[playerSeason] 14108: OK
[playerSeason] 10523: OK
[playerSeason] 14777: OK
[playerSeason] 14778: OK
[playerSeason] 14581: OK
[playerSeason] 16356: OK
[playerSeason] 12916: OK
[playerSeason] 10812: OK
[playerSeason] 10187: OK
[playerSeason] 12534: OK
[playerSeason] 11119: OK
[playerSeason] 16437: OK
[playerSeason] 16447: OK
[playerSeason] 16448: OK
[playerSeason] 16449: OK
[playerSeason] 16568: OK
=== 6. deduplicate season stats ===
season_hit_df.shape = (147, 15)
season_pit_df.shape = (135, 13)
=== 7. clean pitcher season stats ===
=== 8. prepare modeling tables ===
=== 9. build hitter team features ===
hitter_team_features.shape = (0, 0)
=== 10. build starting pitcher features ===
sp_features.shape = (10, 13)
=== 11. make prediction dataframe ===
pred_df.shape = (5, 50)

,game_id,game_date,season,home_team_code,away_team_code,stadium_code,home_sp_id,away_sp_id,home_sp_name,away_sp_name,...,away_sp_KBB,away_sp_QS,away_sp_GS,sp_ERA_diff,sp_FIP_diff,sp_WHIP_diff,sp_K9_diff,sp_BB9_diff,sp_HR9_diff,sp_KBB_diff
0,20260101,2026-04-21 09:30:00,2026,5002,7002,1001,14846,15013,송승기,문동주,...,1.6250,0.0,3.0,-3.91,-1.94441,-0.88,-0.727,-2.795,-0.699,1.6250
1,20260102,2026-04-21 09:30:00,2026,10001,11001,1003,12860,16630,오석주,버하겐,...,2.7500,0.0,3.0,-0.08,2.14327,0.40,0.260,5.106,0.000,-1.7500
2,20260103,2026-04-21 09:30:00,2026,12001,2002,2002,14581,16250,오원석,김태형,...,0.8333,0.0,3.0,-6.35,-5.59412,-1.06,5.558,-3.706,-1.853,8.1667
3,20260104,2026-04-21 09:30:00,2026,1001,9002,7003,11379,16446,최원태,베니지아노,...,1.5000,0.0,3.0,0.80,0.37747,0.21,3.094,0.914,0.535,0.3750
4,20260105,2026-04-21 09:30:00,2026,3001,6002,8001,12930,15143,나균안,벤자민,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
pred_df.isna().sum().sum() # 정상은 10

np.int64(26)

### Non given lineup

In [62]:
sp_df = pd.read_csv("sp_df.csv")

In [59]:
def get_players_by_name(sp_df, names):
    """
    선수명 리스트를 입력하면 해당 행 반환

    Parameters
    ----------
    sp_df : DataFrame (columns: sp_name, sp_id)
    names : list[str] or str

    Returns
    -------
    DataFrame
    """

    # 문자열 하나 들어와도 처리 가능하게
    if isinstance(names, str):
        names = [names]

    result = sp_df[sp_df["sp_name"].isin(names)].copy()

    return result

In [60]:
def get_players_by_name_safe(sp_df, names):
    if isinstance(names, str):
        names = [names]

    result = sp_df[sp_df["sp_name"].isin(names)].copy()

    found_names = set(result["sp_name"])
    missing = list(set(names) - found_names)

    if missing:
        print(f"[경고] 다음 선수는 찾을 수 없음: {missing}")

    return result

In [63]:
names = ["김광현", "김택연", "김진짜"]

get_players_by_name_safe(sp_df, names)

[경고] 다음 선수는 찾을 수 없음: ['김진짜', '김택연']

  sp_name  sp_id
1     김광현  10126

- 선발투수 결측치가 있을 경우 (시즌 첫 등판)

In [5]:
season_pit_df = pd.read_csv('seaon_pit_df.csv')

pred_df = ut.fill_and_recompute_sp_features(
    pred_df=pred_df,
    season_pit_df=season_pit_df,
    target_year=2026
)

In [6]:
pred_df

,game_id,game_date,season,home_team_code,away_team_code,stadium_code,home_sp_id,away_sp_id,home_sp_name,away_sp_name,...,away_sp_GS,sp_ERA_diff,sp_FIP_diff,sp_WHIP_diff,sp_K9_diff,sp_BB9_diff,sp_HR9_diff,sp_KBB_diff,home_sp_imputed,away_sp_imputed
0,20260101,2026-04-21 09:30:00,2026,5002,7002,1001,14846,15013,송승기,문동주,...,3.0,-3.910000,-1.944410,-0.880000,-0.727000,-2.79500,-0.699000,1.625000,0,0
1,20260102,2026-04-21 09:30:00,2026,10001,11001,1003,12860,16630,오석주,버하겐,...,3.0,-0.080000,2.143270,0.400000,0.260000,5.10600,0.000000,-1.750000,0,0
2,20260103,2026-04-21 09:30:00,2026,12001,2002,2002,14581,16250,오원석,김태형,...,3.0,-6.350000,-5.594120,-1.060000,5.558000,-3.70600,-1.853000,8.166700,0,0
3,20260104,2026-04-21 09:30:00,2026,1001,9002,7003,11379,16446,최원태,베니지아노,...,3.0,0.800000,0.377470,0.210000,3.094000,0.91400,0.535000,0.375000,0,0
4,20260105,2026-04-21 09:30:00,2026,3001,6002,8001,12930,15143,나균안,벤자민,...,NaN,-4.371205,-0.775785,-0.318472,-0.415783,-0.41598,-0.361857,-1.849119,0,1

In [7]:
pred_df.isna().sum().sum() # 정상은 10

np.int64(12)

### Logit_full

In [9]:
# feature 순서 맞추기
X_pred = pred_df[feature_cols].copy()

# 홈팀 승리 확률 예측
pred_df["home_win_proba"] = loaded_model.predict_proba(X_pred)[:, 1]

# 보기 좋게 정리
result_df = pred_df[
    [
        "game_id",
        "game_date",
        "home_team_code",
        "away_team_code",
        "home_win_proba"
    ]
].copy()

display(result_df)

    game_id           game_date home_team_code away_team_code  home_win_proba
0  20260066 2026-04-12 05:00:00           5002           9002        0.380774
1  20260067 2026-04-12 05:00:00          10001           3001        0.366464
2  20260068 2026-04-12 05:00:00          12001           6002        0.733135
3  20260069 2026-04-12 05:00:00           7002           2002        0.330097
4  20260070 2026-04-12 05:00:00           1001          11001        0.603055

In [10]:
## 제출 형태

submit_df = result_df[['game_id', 'home_win_proba']].copy()

# 소수점 4자리 반올림 후 *100
submit_df['home_win_proba'] = (submit_df['home_win_proba'].round(4) * 100)

print(submit_df)

    game_id  home_win_proba
0  20260066           38.08
1  20260067           36.65
2  20260068           73.31
3  20260069           33.01
4  20260070           60.31

### logit_model_sp

In [8]:
# feature 순서 맞추기
X_pred_sp = pred_df[feature_cols_sp].copy()

# 홈팀 승리 확률 예측
pred_df["home_win_proba"] = loaded_model_sp.predict_proba(X_pred_sp)[:, 1]

# 보기 좋게 정리
result_df_sp = pred_df[
    [
        "game_id",
        "game_date",
        "home_team_code",
        "away_team_code",
        "home_win_proba"
    ]
].copy()

display(result_df_sp)

    game_id           game_date home_team_code away_team_code  home_win_proba
0  20260101 2026-04-21 09:30:00           5002           7002        0.680463
1  20260102 2026-04-21 09:30:00          10001          11001        0.435620
2  20260103 2026-04-21 09:30:00          12001           2002        0.864516
3  20260104 2026-04-21 09:30:00           1001           9002        0.482132
4  20260105 2026-04-21 09:30:00           3001           6002        0.645262

In [9]:
## 제출 형태

submit_df = result_df_sp[['game_id', 'home_win_proba']].copy()

# 소수점 4자리 반올림 후 *100
submit_df['home_win_proba'] = (submit_df['home_win_proba'].round(4) * 100)

print(submit_df)

    game_id  home_win_proba
0  20260101           68.05
1  20260102           43.56
2  20260103           86.45
3  20260104           48.21
4  20260105           64.53

### API 제출

In [10]:
submit_result_df = sb.submit_predictions_df(
    submit_df,
    path="prediction/savePrediction",     
    sleep_sec=0.2,
    verbose=True
)

display(submit_result_df)

[SUBMIT OK] s_no=20260101, percent=68.05, result_cd=100, result_msg=저장 성공
[SUBMIT OK] s_no=20260102, percent=43.56, result_cd=100, result_msg=저장 성공
[SUBMIT OK] s_no=20260103, percent=86.45, result_cd=100, result_msg=저장 성공
[SUBMIT OK] s_no=20260104, percent=48.21, result_cd=100, result_msg=저장 성공
[SUBMIT OK] s_no=20260105, percent=64.53, result_cd=100, result_msg=저장 성공

,game_id,percent,result_cd,result_msg,raw_response
0,20260101,68.05,100,저장 성공,"{'percent': 68.05, 's_no': '20260101', 'code':..."
1,20260102,43.56,100,저장 성공,"{'percent': 43.56, 's_no': '20260102', 'code':..."
2,20260103,86.45,100,저장 성공,"{'percent': 86.45, 's_no': '20260103', 'code':..."
3,20260104,48.21,100,저장 성공,"{'percent': 48.21, 's_no': '20260104', 'code':..."
4,20260105,64.53,100,저장 성공,"{'percent': 64.53, 's_no': '20260105', 'code':..."

In [71]:
display(result_df)
display(result_df_sp)

    game_id           game_date home_team_code away_team_code  home_win_proba
0  20260041 2026-04-07 09:30:00           6002          10001        0.405185
1  20260042 2026-04-07 09:30:00           9002           7002        0.395980
2  20260043 2026-04-07 09:30:00           2002           1001        0.348821
3  20260044 2026-04-07 09:30:00           3001          12001        0.383156
4  20260045 2026-04-07 09:30:00          11001           5002        0.560368

    game_id           game_date home_team_code away_team_code  home_win_proba
0  20260041 2026-04-07 09:30:00           6002          10001        0.478200
1  20260042 2026-04-07 09:30:00           9002           7002        0.244132
2  20260043 2026-04-07 09:30:00           2002           1001        0.446554
3  20260044 2026-04-07 09:30:00           3001          12001        0.442576
4  20260045 2026-04-07 09:30:00          11001           5002        0.535654

In [5]:
def predict_single_game(model, feature_cols, game_dict):
    df = pd.DataFrame([game_dict])
    df = df[feature_cols]
    proba = model.predict_proba(df)[:, 1][0]
    return proba

In [ ]:
proba = predict_single_game(loaded_model, feature_cols, new_game)
print(proba)